-- 补充数据
SET @beginTime='2016-09-30'; 
SET @endTime='2016-10-06';
SET @currTime='2016-10-07';


-- insert

INSERT into t_rpt_overview(PERIOD_TYPE,PERIOD_NAME,DEVICE_TYPE,APP_VERSION,CHANNEL_NO,SECOND_DNUM,ONLINE_UNUM,DEVICE_NUM,ACTIVE_DNUM)
SELECT t.PERIOD_TYPE,@currTime,t.DEVICE_TYPE,t.APP_VERSION,t.CHANNEL_NO, CEIL(SUM(t.SECOND_DNUM)/7), CEIL(SUM(t.ONLINE_UNUM)/7), CEIL(SUM(t.DEVICE_NUM)/7), CEIL(SUM(t.ACTIVE_DNUM)/7)
FROM t_rpt_overview t
WHERE t.PERIOD_TYPE=1 AND t.PERIOD_NAME>=@beginTime AND t.PERIOD_NAME<=@endTime
GROUP BY t.PERIOD_TYPE,t.DEVICE_TYPE,t.APP_VERSION,t.CHANNEL_NO
on duplicate key update 
SECOND_DNUM = values(SECOND_DNUM),
ONLINE_UNUM = values(ONLINE_UNUM),
DEVICE_NUM = values(DEVICE_NUM),
ACTIVE_DNUM = values(ACTIVE_DNUM)




