stat_time,channel_no,device_num,online_unum,first_dnum,second_dnum,active_dnum,reg_unum,first_buy_unum,first_buy_amount,buy_unum,buy_amount,
first_srv_unum,first_srv_amount,srv_unum,srv_amount,first_bcoin_unum,first_bcoin_amount,buycoin_unum,buycoin_amount,visual_status,
device_pv,device_uv,
diamond_user_cnt,diamond_recharge_sum,
ft_bet_users,ft_bet_counts,ft_bet_coins,ft_return_coins,
bk_bet_users,bk_bet_counts,bk_bet_coins,bk_return_coins;

CREATE TABLE `t_rpt_third_overview` (
	`stat_time` date,
	`channel_no` VARCHAR(50) NULL DEFAULT NULL ,
	`visual_status` INT(4) NOT NULL DEFAULT 1,
	`device_num` INT(11) NULL DEFAULT NULL,
	`online_unum` INT(11) NULL DEFAULT NULL,
	`first_dnum` INT(11) NULL DEFAULT NULL,
	`second_dnum` INT(11) NULL DEFAULT NULL,
	`active_dnum` INT(11) NULL DEFAULT NULL,
	`reg_unum` INT(11) NULL DEFAULT NULL,
	`first_buy_unum` INT(11) NULL DEFAULT NULL,
	`first_buy_amount` INT(11) NULL DEFAULT NULL,
	`buy_unum` INT(11) NULL DEFAULT NULL,
	`buy_amount` INT(11) NULL DEFAULT NULL,
	`first_srv_unum` INT(11) NULL DEFAULT NULL,
	`first_srv_amount` INT(11) NULL DEFAULT NULL,
	`srv_unum` INT(11) NULL DEFAULT NULL,
	`srv_amount` INT(11) NULL DEFAULT NULL,
	`first_bcoin_unum` INT(11) NULL DEFAULT NULL,
	`first_bcoin_amount` INT(11) NULL DEFAULT NULL,
	`buycoin_unum` INT(11) NULL DEFAULT NULL,
	`buycoin_amount` INT(11) NULL DEFAULT NULL,
	`device_pv` INT(11) NULL DEFAULT NULL,
	`device_uv` INT(11) NULL DEFAULT NULL,
	`diamond_user_cnt` INT(11) NULL DEFAULT NULL,
	`diamond_recharge_sum` INT(11) NULL DEFAULT NULL,
	`ft_bet_users` INT(11) NULL DEFAULT NULL,
	`ft_bet_counts` INT(11) NULL DEFAULT NULL,
	`ft_bet_coins` INT(11) NULL DEFAULT NULL,
	`ft_return_coins` INT(11) NULL DEFAULT NULL,
	`bk_bet_users` INT(11) NULL DEFAULT NULL,
	`bk_bet_counts` INT(11) NULL DEFAULT NULL,
	`bk_bet_coins` INT(11) NULL DEFAULT NULL,
	`bk_return_coins` INT(11) NULL DEFAULT NULL,
	UNIQUE INDEX `IDX_RPT_OVERVIEW_1` (`stat_time`, `channel_no`)
)


CREATE TABLE `t_rpt_channel_discount` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`CHANNEL_NAME` VARCHAR(50) NOT NULL COMMENT '渠道名称',
	`CHANNEL_NO` VARCHAR(30) NOT NULL COMMENT '渠道编码',
	`device_num` DOUBLE NOT NULL DEFAULT 1 ,
	`online_unum` DOUBLE NOT NULL DEFAULT 1 ,
	`first_dnum` DOUBLE NOT NULL DEFAULT 1,
	`second_dnum` DOUBLE NOT NULL DEFAULT 1,
	`active_dnum` DOUBLE NOT NULL DEFAULT 1,
	`reg_unum` DOUBLE NOT NULL DEFAULT 1,
	`first_buy_unum` DOUBLE NOT NULL DEFAULT 1,
	`first_buy_amount` DOUBLE NOT NULL DEFAULT 1,
	`buy_unum` DOUBLE NOT NULL DEFAULT 1,
	`buy_amount` DOUBLE NOT NULL DEFAULT 1,
	`first_srv_unum` DOUBLE NOT NULL DEFAULT 1,
	`first_srv_amount` DOUBLE NOT NULL DEFAULT 1,
	`srv_unum` DOUBLE NOT NULL DEFAULT 1,
	`srv_amount` DOUBLE NOT NULL DEFAULT 1,
	`first_bcoin_unum` DOUBLE NOT NULL DEFAULT 1,
	`first_bcoin_amount` DOUBLE NOT NULL DEFAULT 1,
	`buycoin_unum` DOUBLE NOT NULL DEFAULT 1,
	`buycoin_amount` DOUBLE NOT NULL DEFAULT 1,
	`device_pv` DOUBLE NOT NULL DEFAULT 1,
	`device_uv` DOUBLE NOT NULL DEFAULT 1,
	`diamond_user_cnt` DOUBLE NOT NULL DEFAULT 1,
	`diamond_recharge_sum` DOUBLE NOT NULL DEFAULT 1,
	`ft_bet_users` DOUBLE NOT NULL DEFAULT 1,
	`ft_bet_counts` DOUBLE NOT NULL DEFAULT 1,
	`ft_bet_coins` DOUBLE NOT NULL DEFAULT 1,
	`ft_return_coins` DOUBLE NOT NULL DEFAULT 1,
	`bk_bet_users` DOUBLE NOT NULL DEFAULT 1,
	`bk_bet_counts` DOUBLE NOT NULL DEFAULT 1,
	`bk_bet_coins` DOUBLE NOT NULL DEFAULT 1,
	`bk_return_coins` DOUBLE NOT NULL DEFAULT 1,
	`BEGIN_TIME` DATETIME NULL DEFAULT NULL COMMENT '起始日期',
	`END_TIME` DATETIME NULL DEFAULT NULL COMMENT '结束日期',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `idx_channel_no` (`channel_no`)
)