金币
"ACT_PRIZE" -抽奖活动派奖
"ADMIN_USER_OPT"-后台操作
"COIN_FROM_DIAMEND"-钻石兑换游戏币
"BUY_ACT_TIMES"-抽奖次数购买
"COIN_PRESENT"-充值赠送游戏币
"COIN_REDEEM"-兑换
"CP_PRIZE"-赏金答题派奖
"CP_TRADE"-赏金答题扣减
"FG_GAME_PRIZE"-石头剪刀布派奖
"FG_GAME_TRADE"-石头剪刀布扣减
"GET_FREE_COIN"-免费领取(包括来免费领取钻石和金币)
"PRESENT_FROM_USER"-赠送获得
"USER_PRESENT"-赠送
"PRIZE_COIN"-下注派奖
"TRADE_COIN"-下注
"TRANSFER"-转账
"TRANSFER-OUT"-转账
"VIP_PRESENT"-购买VIP赠送
"USER_GROUP_PRIZE"-邀请领取

钻石
"BUY_DIAMEND"-购买钻石
"BUY_RECOM"-购买推荐
"ADMIN_USER_OPT"-后台操作
"BUY_DIAMEND"-购买钻石
"*-REFUND"-撤单
"BUY_SERVICE"-购买解盘，平局，亚盘服务
"DIAMEND_PRESENT"-钻石充值赠送
"DIAMEND_TO_COIN"-钻石兑换游戏币
"BUY_VIP"-购买VIP服务


移动活动抽奖送金币和钻石
item_event:ACT_L_CMCC

ITEM_EVENT：USER_TASK  任务体系获取金币   
ITEM_EVENT：USER_TASK_LOTTERY  任务体系抽奖获得


ITEM_TYPE：CLUBS_CREATE//创建
CLUBS_RENEW//续期
CLUBS_LEVEL//升级


ROOM_ADD_ASSETS_TRANSFER  房间场追加资产
ROOM_CREATE_TRANSFER  创建房间
ROOM_PACKET_TRADE  发起红包
PACKET_RECIVE  领取红包
PCKET_EXPIRE  红包到期退款
ROOM_CLOSE_TRANSFER  房间关闭退款
RE_ROOM_MONEY  房间订单重算     PK_TRADE_COIN_USER
PK_TRADE_COIN_SYS
PK_PRIZE_COIN_USER
PK_PRIZE_COIN_SYS
