SELECT '常规赠送金币数',DATE(s.ADD_TIME) AS _date, CAST(IFNULL(SUM(s.change_value),0) AS DECIMAL(10,0)) `常规赠送金币数`
FROM forum.t_acct_items s
WHERE 
    s.ITEM_EVENT='GET_FREE_COIN' 
AND s.ITEM_STATUS=10 
AND (s.TRADE_NO
LIKE '%BUY_SRV%' 
OR s.TRADE_NO 
LIKE '%ADD_NOTE%' 
OR s.TRADE_NO 
LIKE '%FOLLOW_CIRCLE%' 
OR s.TRADE_NO 
LIKE 'USER_GJ-%' 
OR s.TRADE_NO 
LIKE 'SIGN_%' 
OR s.TRADE_NO = 'BIND_BIND' 
OR s.TRADE_NO = 'NEWTASK1000_NEWTASK1000')
GROUP BY _date;
