CREATE TABLE `t_channel_add` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`STAT_TIME` VARCHAR(50) NULL DEFAULT NULL COMMENT '时间',
	`CHANNEL_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '渠道名',
	`CHANNEL_NO` VARCHAR(50) NULL DEFAULT NULL COMMENT '渠道包',
	`CHANNEL_COMPANY` VARCHAR(50) NULL DEFAULT NULL COMMENT '公司名',
	`terminal_type` VARCHAR(50) NULL DEFAULT NULL COMMENT '终端',
	`CHANNEL_ORDER` VARCHAR(50) NULL DEFAULT NULL COMMENT '渠道序号',
	`CHANNEL_version` VARCHAR(50) NULL DEFAULT NULL COMMENT '版本号',
	`CHANNEL_TYPE` VARCHAR(50) NULL DEFAULT NULL COMMENT '渠道类型',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=250
;



INSERT INTO `t_device_channel` (`CHANNEL_NO`, `CHANNEL_NAME`, `SYSTEM_MODEL`, `STATUS`, `CHANNEL_TYPE`, `DL_URL`, `CHANNEL_LEVEL`, `GLOBAL_VIEWED_ORDER`, `COMPANY_NAME`) 
select ta.CHANNEL_NO,ta.CHANNEL_NAME,ta.terminal_type,10,ta.CHANNEL_TYPE,null,null,ta.CHANNEL_ORDER,ta.CHANNEL_COMPANY from t_channel_add ta
on duplicate key update 
CHANNEL_NO = values(CHANNEL_NO),
CHANNEL_NAME = values(CHANNEL_NAME),
SYSTEM_MODEL = values(SYSTEM_MODEL),
`STATUS` = values(`STATUS`),
CHANNEL_TYPE = values(CHANNEL_TYPE),
DL_URL = values(DL_URL),
GLOBAL_VIEWED_ORDER = values(GLOBAL_VIEWED_ORDER),
COMPANY_NAME = values(COMPANY_NAME)
