CREATE TABLE `t_group_ref` (
	`REF_ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`LAST_ID` BIGINT(19) NULL DEFAULT NULL,
	`ROOT_ID` BIGINT(19) NULL DEFAULT NULL,
	`USER_ID` VARCHAR(50) NULL DEFAULT NULL,
	`CRT_TIME` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_TIME` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`REF_STATUS` INT(2) NULL DEFAULT NULL,
	`SOURCE` VARCHAR(50) NULL DEFAULT NULL,
	`JOIN_TYPE` VARCHAR(50) NULL DEFAULT NULL,
	`BEFOR_REF_ID` BIGINT(19) NULL DEFAULT NULL COMMENT '修改关联的上一个人id',
	`COMMENTS` VARCHAR(200) NULL DEFAULT NULL,
	`ADD_TIME` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`REF_ID`),
	UNIQUE INDEX `USER_ID` (`USER_ID`),
	INDEX `ROOT_ID` (`ROOT_ID`),
	INDEX `LAST_ID` (`LAST_ID`),
	INDEX `CRT_TIME` (`CRT_TIME`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=428530
;
