CREATE TABLE `t_ip_address` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`start_ip` VARCHAR(20) NOT NULL,
	`end_ip` VARCHAR(20) NOT NULL,
	`ip_address` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=42235
;