CREATE TABLE `t_user_tag_static` (
	`user_id` BIGINT(20) NOT NULL COMMENT '在forum的ID',
	`user_code` BIGINT(20) NULL DEFAULT NULL COMMENT '在game的ID',
	`nick_name` VARCHAR(500) NULL DEFAULT NULL COMMENT '昵称',
	`real_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '真实名字',
	`user_sign` VARCHAR(500) NULL DEFAULT NULL COMMENT '签名',
	`gender` INT(11) NULL DEFAULT NULL COMMENT '性别',
	`address` VARCHAR(500) NULL DEFAULT NULL COMMENT '联系地址',
	`email` VARCHAR(500) NULL DEFAULT NULL COMMENT '联系邮箱',
	`user_type` INT(11) NULL DEFAULT NULL COMMENT '用户类型',
	`user_level` INT(11) NULL DEFAULT NULL COMMENT '用户级别',
	`expert_level` INT(11) NULL DEFAULT NULL COMMENT '专家级别',
	`alipay` VARCHAR(500) NULL DEFAULT NULL COMMENT '支付宝账号',
	`wechat` VARCHAR(500) NULL DEFAULT NULL COMMENT '微信账号',
	`education` INT(11) NULL DEFAULT NULL COMMENT '受教育程度',
	`marriage` INT(11) NULL DEFAULT NULL COMMENT '婚姻状态',
	`id_code` VARCHAR(500) NULL DEFAULT NULL COMMENT '身份证号码',
	`id_area` VARCHAR(500) NULL DEFAULT NULL COMMENT '身份证对应地区',
	`id_age` INT(11) NULL DEFAULT NULL COMMENT '身份证上体现的年龄',
	`bank_type` VARCHAR(500) NULL DEFAULT NULL COMMENT '银行类型',
	`bank_no` VARCHAR(500) NULL DEFAULT NULL COMMENT '银行卡号',
	`bank_branch` VARCHAR(500) NULL DEFAULT NULL COMMENT '银行支行',
	`reg_time` DATETIME NULL DEFAULT NULL COMMENT '注册时间',
	`reg_channel_no` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册渠道编号',
	`reg_app_version` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的APP版本',
	`reg_mobile_no` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的手机号',
	`reg_mobile_no_area` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的手机号的归属地',
	`reg_mobile_brand` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的手机品牌',
	`reg_mobile_os` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的手机操作系统',
	`reg_mobile_os_version` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的手机操作系统版本',
	`reg_mobile_name` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的手机名称',
	`reg_device_code` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的手机设备号',
	`reg_ip` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的ip',
	`reg_ip_address` VARCHAR(500) NULL DEFAULT NULL COMMENT '注册时的ip对应地址',
	`revenue_level` INT(11) NULL DEFAULT NULL COMMENT '收入情况',
	`diamond` DECIMAL(10,4) NULL DEFAULT NULL COMMENT '账号里的钻石余额',
	`coin_free` DECIMAL(10,4) NULL DEFAULT NULL COMMENT '体验币余额',
	`coin` DECIMAL(10,4) NULL DEFAULT NULL COMMENT '金币',
	`usage_status` INT(11) NULL DEFAULT NULL COMMENT '该用户数据被废弃, -1是， 0不是',
	PRIMARY KEY (`user_id`)
)
COMMENT='用户静态属性标签'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
